pdf:
	pdflatex sbc-template.tex
	biber sbc-template
	pdflatex  sbc-template.tex
	pdflatex  sbc-template.tex


clean:
	rm -f *~ *.log *.aux *.dvi *.bbl *.blg *.cb *.dep *.bcf *.run.xml sbc-template.pdf
